print("--" * 30)
print("this is my day 1")
print("--" * 30)
thought = input("whats on your mind ? ")
print(f"nice that is grat that u thoucht about {thought}")
print("--" * 30)
print("following is the different types of the variables")
print(f"type of elon is {type("elon")}")
print(f"type of 5 is {type("5")}")
print(f"type of 5.5555555555 is {type("5.5555555555")}")
print(f"type of True is {type(True)}")
print(f"type of A is {type('A')}")
print(f"type of '45' is {type("45")}")
print("--" * 30)